FROM nginxinc/nginx-unprivileged:stable-alpine

LABEL author="Mohammad Naghavi <mohamnag@gmail.com>"

ADD default-rootless.conf /etc/nginx/conf.d/default.conf
ADD css/ /opt/www/file-browser/css/
ADD image/ /opt/www/file-browser/image/
ADD js/ /opt/www/file-browser/js/
ADD index.html /opt/www/file-browser/

VOLUME /opt/www/files/
EXPOSE 8080